### ISSUE TITLE
handleFiles won't trigger if the same file is selected twice

### ISSUE THREAD

**Issue by jonathanmv** [GrillWork/react-file-reader#10]
Hi, first of all thanks for creating and sharing this component.

I noticed that if you select a file the handleFiles listener is called as expected, however, if I retry the action of selecting the same file to upload, handleFiles won't get called. 
I double checked this behaviour on your demo page. You can check it too by selecting a file with the console open, then clearing the messages in the console and retrying the process. You will notice that no new messages are shown after selecting the same file.

As a side note, selecting the same image to upload doesn't make much sense, however it's important for my users to select the same file several times.

**Comment by travisdmathis** [comment]
@jonathanmv thanks for bringing this to our attention. We'll get it taken care of.

**Comment by travisdmathis** [comment]
@jonathanmv this was fixed in the latest release v1.1.2 https://github.com/GrillWork/react-file-reader/pull/11

please give it a shot and let me know if you have any further issues..

Thanks
